const modal=document.getElementById('modal'),content=document.getElementById('toolContent');
const phrases=['DIGITAL CREATOR','CODE • BUILD • CREATE','WELCOME TO JOKER RKS'];let p=0,i=0,d=false;
function loop(){let t=phrases[p];document.getElementById('typing').textContent=d?t.slice(0,--i):t.slice(0,++i);let s=d?45:85;if(!d&&i===t.length){d=true;s=1300}else if(d&&i===0){d=false;p=(p+1)%phrases.length;s=350}setTimeout(loop,s)}loop();
document.getElementById('hamb').onclick=()=>document.getElementById('nav').classList.toggle('mobile');
function toggleTheme(){document.body.classList.toggle('soft')}
function closeTool(){modal.classList.remove('show');content.innerHTML=''}
function openTool(type){modal.classList.add('show');
if(type==='pass')content.innerHTML=`<h3>01 // PASSWORD STRENGTH</h3><p>Check the strength of a password locally.</p><input id="p" type="password" placeholder="Enter password"><div class="result" id="pr">Strength: —</div>`;document.getElementById('p').oninput=()=>{let v=p.value,s=0;if(v.length>=8)s++;if(v.length>=12)s++;if(/[A-Z]/.test(v)&&/[a-z]/.test(v))s++;if(/\d/.test(v))s++;if(/[^A-Za-z0-9]/.test(v))s++;let a=['—','Very weak','Weak','Fair','Strong','Very strong'];document.getElementById('pr').textContent='Strength: '+a[s]};
if(type==='base')content.innerHTML=`<h3>02 // BASE64 LAB</h3><textarea id="bi" placeholder="Enter text..."></textarea><button class="action" onclick="enc()">ENCODE</button><button class="action" onclick="dec()">DECODE</button><button class="action" onclick="copy('bo')">COPY</button><div class="result" id="bo">Result...</div>`;
if(type==='gen')content.innerHTML=`<h3>03 // RANDOM PASSWORD</h3><p>Choose a length and generate a random password.</p><input id="gl" type="range" min="6" max="40" value="16"><div class="result"><span id="gv">Length: 16</span></div><button class="action" onclick="gen()">GENERATE</button><button class="action" onclick="copy('gr')">COPY</button><div class="result" id="gr">Click generate</div>`;if(document.getElementById('gl'))document.getElementById('gl').oninput=e=>document.getElementById('gv').textContent='Length: '+e.target.value;
if(type==='qr')content.innerHTML=`<h3>04 // QR GENERATOR</h3><input id="qi" placeholder="Enter text or link"><button class="action" onclick="qr()">GENERATE QR</button><div class="qr-result" id="qr"></div><p>QR image is requested from an external QR service.</p>`;
if(type==='calc')content.innerHTML=`<h3>05 // DEV CALCULATOR</h3><input id="cd" readonly value="0"><div class="calc-grid">${['C','⌫','%','÷','7','8','9','×','4','5','6','−','1','2','3','+','0','.','='].map(x=>`<button onclick="cal('${x}')">${x}</button>`).join('')}</div>`}
function enc(){try{document.getElementById('bo').textContent=btoa(unescape(encodeURIComponent(document.getElementById('bi').value)))}catch(e){document.getElementById('bo').textContent='Invalid input'}}
function dec(){try{document.getElementById('bo').textContent=decodeURIComponent(escape(atob(document.getElementById('bi').value)))}catch(e){document.getElementById('bo').textContent='Invalid Base64'}}
async function copy(id){try{await navigator.clipboard.writeText(document.getElementById(id).textContent);alert('Copied')}catch(e){}}
function gen(){let n=+document.getElementById('gl').value,c='ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%^&*',r='';for(let x=0;x<n;x++)r+=c[Math.floor(Math.random()*c.length)];document.getElementById('gr').textContent=r}
function qr(){let v=document.getElementById('qi').value.trim();document.getElementById('qr').innerHTML=v?`<img src="https://api.qrserver.com/v1/create-qr-code/?size=180x180&data=${encodeURIComponent(v)}" alt="QR code">`:'Enter text or link'}
let expression='';function cal(x){let d=document.getElementById('cd');if(x==='C')expression='';else if(x==='⌫')expression=expression.slice(0,-1);else if(x==='='){try{if(!/^[0-9+\-*/%.() ]+$/.test(expression))throw 0;expression=String(Function('return ('+expression.replace(/×/g,'*').replace(/÷/g,'/')+')')())}catch(e){expression='ERROR'}}else expression+=x.replace('×','*').replace('÷','/').replace('−','-');d.value=expression||'0'}
for(let n=0;n<45;n++){let e=document.createElement('i');e.className='particle';e.style.left=Math.random()*100+'%';e.style.animationDuration=8+Math.random()*12+'s';document.getElementById('particles').appendChild(e)}
                                                                                                                      
